name: Monthly Check

on:
  push:
  schedule:
    - cron: '0 8 1 * *'  # Run at 08:00 UTC on the 1st of every month
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - uses: mattvenn/z2a-course-regressions@main
        with:
          repo: mattvenn/magic-mosfet-refresh25
          ref: mosfet-ci
          command: make check
          artifact_file: mosfet.svg

